options {
  directory "/var/cache/bind";
  listen-on { any; };
  listen-on-v6 { none; };
  recursion yes;
  allow-query { any; };
  forwarders { 1.1.1.1; 8.8.8.8; };
};
zone "asir.test" {
  type primary;
  file "/etc/bind/db.asir.test";
};
