services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:15.1.0
    hostname: mail
    domainname: asir.test
    container_name: sri-ut6-mailserver
    env_file: mailserver.env
    ports:
      - "2525:25"
      - "2587:587"
      - "2993:993"
      - "2995:995"
    volumes:
      - mail-data:/var/mail/
      - mail-state:/var/mail-state/
      - mail-logs:/var/log/mail/
      - mail-config:/tmp/docker-mailserver/
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD-SHELL", "ss -lnt | grep -q ':25 '"]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  mail-data:
  mail-state:
  mail-logs:
  mail-config:
